apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tododomain-weblogic-credentials
  namespace: mc-todo-list
spec:
  encryptedData:
    password: AgBi589rEewChphP3fUhNLAT0lu8p97u2r5e5URiPDkrLK6QvUiZ72VUtt0WfeSpk+NVJBjDobqpDVQYuTr3Wrz0pfBshyPDNn02rYFXZqwgDdt6pRQvZS9hlnuhPzESTpkTiR5vEsMiq+2vcKj9ICGPZp45mung1BGu3zTTaPUXtG5RN0Xa5xsITuuRFEBKrp5wYvX6bls4qHgx1Xt1LHjPaKvjcz13bMWtEicKa6gf82gU+g7PQRPO072Ou1N6JjjdjaXkAF9xVYfTt8i4urK52VLzS3b5rGGQ84SCrUIquO1n59g97lMJ9oB4ljhZ53nFeNQ6eJrq1NTWCF8QtI51AeafTJhemESnrz9mjPNqjeVIQNF9sfirb18fp3An1exprCs34MeH/+Ljuaa/j9Bur1wk+jMQUF3P4XfxDL+W34LV8yjEJuamhEiIWafaU9Z+YRdMqNJ306l9GJ8imAPYQ2uGmRh7JGlE2UhUinPo+25JhFDvVrcpUmxQG1wH4GI5YH7AVUddKV+a+Eb7GvGn2Nq18zVn8ibHS6+pz2o9haPFtmE2+QU/7XZO3n2Mq1AsFvZ5S3WJbcUQHKp0oFiKSSPjh33mbGqlWZDzGuFm8+C+IcWPE/IQbpr9r7V6QnZYfC/mxh0Ksqi3KKGyqyqLKCZEa/iQkdd6Iz3sd2IDdJP1m7Tj9f9y1Qf3uwMh/8xfFZWEZOk8kQ==
    username: AgCBphY7keYPoYQZ6N+mJy1t01Vf8S3P1qYhBbivfnhhgdc13ZyLO68Qs2LTwZ4UTIdSn2m7Dyzutb3BplDpKNd/1N0Ugx83n0m2FKhdslH5YeVo+SEAFqMI8nIM7IHUeOsyTd1CmGJuB1HVudFPAX+Pf/KLN8/Gt/fEsHkFzroDiV613YPmW81iHbr5FbhmB7VUNlghGwGP+wdcvyXo7ZSdJGC6//JP5txpXTt/iILJ/baxar1qDd/WlqzsNxTBu3uQ9sjl58T6sky52UOUhtK2RrYyYkdxx33D2bjdv36ifcE/IPQQvRR7mUIwA99zabkPVaNrj2jZhQRf9tsatuP9CWlLaRXASQRisXHaRXfdrhQkt6VRPMkbZ70vFRxvDyP74CNSpd2N1EO/mI9t9+NPPjr+2WjYBMpm9QJx1ypblkdcKmVmyt4eLJBf7IFWyuDj0krzhW+gQzB8b6hVjWTJMFsb5+RE3FEJG4KOse5DxFaYUs5xn2QjrCIQgKRz2OTHiAJlkXz7jXatoqaK1LuAtIkgd3iO4ZvGwmhSUExb5t1tj2QtshrIV4evKw6TRSOiSjaWfVWMZlPDqevFWklruSLLeX3Zkro5Z9gJf95bi2RdGRxZtfTaQqsouKpjl6gEnOXCIkqzNgjhcUeFf9OI6/sy1txMH5YHZXfpMIGUaoOsgp7lZFpW0LH526e4nl2kmGzX0J1eRQ==
  template:
    metadata:
      creationTimestamp: null
      name: tododomain-weblogic-credentials
      namespace: mc-todo-list
    type: Opaque

